spring:
  application: 
    name: dubbo-spring-boot-consumer
dubbo: 
  application: 
    name: dubbo-spring-boot-consumer
  registry: 
    address: zookeeper://localhost:2181
  protocol: 
    name: dubbo
    port: 20881
  consumer: 
    timeout: 20000